### ISSUE TITLE
コンストラクタで受け取った引数がセットされない

### ISSUE THREAD

**Issue by kooomaaaaaa** [reima4038/SpringDataJPAUniqueConstraintsInspection#1]
https://github.com/reima4038/SpringDataJPAUniqueConstraintsInspection/blob/30dd2c80859dad1caf51bc96468d031d20805cb0/src/main/java/com/example/demo/domain/Book.java#L19

以下がないのでevilUpdateでnewしたときに、nullになる。
```
this.id=id;
this.storeName=storeName;
```

**Comment by reima4038** [comment]
単体テストを真面目に書かないとこういうの見逃すという例。
